services:
  aa.com:
    container_name: talkn-ch-gateway-aa.com
    image: nginx:alpine
    volumes:
      - /Users/hiroyukimiyazaki/talkn-ch-gateway/common/ch-configs/aa.com/nginx.conf:/etc/nginx/nginx.conf
      - /Users/hiroyukimiyazaki/talkn-ch-gateway/common/ch-configs/aa.com/openssl.crt:/etc/ssl/certs/openssl.crt
      - /Users/hiroyukimiyazaki/talkn-ch-gateway/common/ch-configs/aa.com/openssl.key:/etc/ssl/certs/openssl.key
    ports:
      - "10001:443"
    environment:
      - IS_DOCKER=true
      - NODE_ENV=development
    command: ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]
    deploy:
      resources:
        limits:
          memory: 2g
    networks:
      - talkn-global

networks:
  talkn-global:
    external: true
