services:
  io-dd.com:
    container_name: talkn-ch-server-io-dd.com
    image: node:22.2.0
    depends_on:
      - redis
    external_links:
      - talkn-ch-server-redis:redis
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - ~/talkn-ch-gateway/common/ch-configs/dd.com/openssl.crt:/etc/ssl/certs/openssl.crt
      - ~/talkn-ch-gateway/common/ch-configs/dd.com/openssl.key:/etc/ssl/certs/openssl.key
    command: sh -c "npm install && npm run dev"

    environment:
      - IS_DOCKER=true
      - TOP_CONNECTION=/dd.com/
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - talkn-global

networks:
  talkn-global:
    external: true

